### ISSUE TITLE
Screen is to small

### ISSUE THREAD

**Issue by DrkPhoenix76** [IceWolf777/Nuclearcraft-Reactor-UI-ControlPanel#4]
When I went to put it on my computer the screen ended up being too small and the display isn't working all too well. If I could get some help it would be much appreciated. 
![16790298443488359508752690104272](https://user-images.githubusercontent.com/128119456/225818053-6475bdec-3bc8-448e-bf7f-aedbdca22f20.jpg)

**Comment by CastilloAnthony** [comment]
Try attaching a second screen to the right of the one you're using. I designed the UI so that it could be scaled up infinitely, so it should look good when you have more than one monitor attached. Unfortunately, due to the amount of information that I wanted to have displayed at all times I was unable to get it to look good when only using one small screen. Regardless of that, the monitoring system should still be functioning properly.
